version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - default
    restart: always
    ports:
       - "10050:80"
  mysql:
    image: mariadb
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genesis-test
    networks:
      - default
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpMyAdmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: 127.0.0.1
    networks:
      - default
    links:
      - mysql:db
    depends_on:
      - "mysql"
    ports:
       - "10500:80"
  php:
    container_name: ${PROJECT_NAME}-php
    restart: always
    volumes:
      - ./:/var/www
    build: ./docker/php
    networks:
      - default
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: genesis-test
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    depends_on:
      - "mysql"
  rabbitmq:
    image: rabbitmq:3.6.1-management
    container_name: ${PROJECT_NAME}-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - default